language: cpp

# Save time by only getting the current repository status
git:
  depth: false

dist: xenial

# Test both clang and gcc
compiler:
  - clang
  - gcc

# Install requirements with apt
addons:
  apt:
    update: true
    packages:
    - ncurses-base
    - libncurses-dev
    - valgrind
    - automake
    - autoconf
    - perl
    - m4
    - autoconf-archive

# Actually check if it works
script:
  - autoreconf -f && ./configure && make && make check
  - if [ -x "src/simple_test" ]; then make clean; cd src; make CXXFLAGS=-DVALGRIND_DEBUG simple_test; valgrind --leak-check=full --show-leak-kinds=all ./simple_test; fi
