language: cpp

# Save time by only getting the current repository status
git:
  depth: false

# Test both clang and gcc
compiler:
  - clang
  - gcc

# Test both linux and osx
os:
  - linux
  - osx

# Install requirements with apt
addons:
  apt:
    update: true
    packages:
    - ncurses-base
    - libncurses-dev
    - valgrind
    - automake
    - autoconf
    - perl
    - m4
    - autoconf-archive
  homebrew:
    packages:
    - ncurses-base
    - libncurses-dev
    - valgrind
    - automake
    - autoconf
    - perl
    - m4
    - autoconf-archive

# Actually check if it works
script:
  - automake -a && ./configure && make && make check && valgrind src/simple_test
