language: cpp

# Save time by only getting the current repository status
git:
  depth: false

# Test both clang and gcc
compiler:
  - clang
  - gcc

# Test both linux and osx
os:
  - linux
  - osx

# Install requirements with apt
addons:
  apt:
    update: true
    packages:
    - ncurses-base
    - libncurses-dev
    - valgrind
  homebrew:
    packages:
    - ncurses-base
    - libncurses-dev
    - valgrind

# Actually check if it works
script:
  - ./configure && make && make check
  - valgrind src/simple_test
