name: Test Workflow

on:
  push:
    paths: [ '.github/workflows/test.yml', 'CMakeLists.txt', 'src/**' ]
  pull_request:
    paths: [ '.github/workflows/test.yml', 'CMakeLists.txt', 'src/**' ]

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        generator: [ 'Ninja', 'Unix Makefiles' ]
        compiler: [ 'g++', 'clang++' ]
        exclude:
        - os: windows-latest
          generator: 'Unix Makefiles'
        - os: windows-latest
          compiler: clang++
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install APT packages.
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ncurses-dev cmake
    - name: Cache Windows packages.
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        key: vcpkg-${{ matrix.compiler }}
        path: C:\vcpkg\archives
    - name: Install Windows packages.
      if: matrix.os == 'windows-latest'
      run: |
        vcpkg install pdcurses --binarysource=files,C:/vcpkg/archives
      shell: sh
    - name: CMake Configure
      run: |
        cmake --version
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=TRUE -DCMAKE_BUILD_PARALLEL_LEVEL=2 -DCMAKE_VERBOSE_MAKEFILE=TRUE -DFETCHCONTENT_QUIET=OFF ..
      env:
        CXX: ${{ matrix.compiler }}
        GENERATOR: ${{ matrix.generator }}
      shell: sh
    - name: CMake Build
      run: |
        cd build
        cmake --build .
      shell: sh
    - name: CTest
      run: |
        cd build
        ctest -j2 -VV
      shell: sh
